[project]
name = "mixed-precision-rl"
version = "0.1.0"
description = "Figuring out mixed precision in RL"
readme = "README.md"
requires-python = ">=3.13.11"
dependencies = [
    "distrax>=0.1.9",
    "jax[cuda13]>=0.10.2",
    "jaxtyping>=0.3.11",
    "optax>=0.2.8",
    "playground>=0.2.0",
    "tyro>=1.0.15",
    "wandb>=0.28.0",
]
