[project]
name = "mixed-precision-rl"
version = "0.1.0"
description = "Figuring out mixed precision in RL"
readme = "README.md"
requires-python = ">=3.13.11"
dependencies = [
    "craftax>=1.6.1",
    "distrax>=0.1.9",
    "jaxtyping>=0.3.11",
    "optax>=0.2.8",
    "playground>=0.2.0",
    "stoa-env>=0.1.2",
    "tyro>=1.0.15",
    "wandb>=0.28.0",
    "warp-lang==1.13.0",
]

[dependency-groups]
cuda12 = ["jax[cuda12]>=0.10.2"]
cuda13 = ["jax[cuda13]>=0.10.2"]
dev = [
    "pytest>=9.0.2",
]

[tool.uv]
default-groups = ["dev", "cuda13"]
conflicts = [
    [
        { group = "cuda12" },
        { group = "cuda13" },
    ],
]

[tool.ruff]
ignore = ["F722", "E731"]
ignore-init-module-imports = true

[tool.ruff.lint.isort]
section-order = ["future", "standard-library", "jax", "third-party", "first-party", "local-folder"]
order-by-type = false
force-sort-within-sections = true

[tool.ruff.lint.isort.sections]
jax = ["jax", "jaxtyping", "optax", "flax", "distrax"]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
addopts = ["--capture=sys"]
